[package]
name = "hello"
version = "0.1.0"
authors = ["Eric Gustafson <ericg@elfwerks.io>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
