@ Generated by gcc 2.95.3 20010315 (release) for ARM/elf
	.file	"rol.c"
gcc2_compiled.:
.section	.rodata
	.align	2
.LC0:
	.ascii	"%3d : 0x%08x\012\000"
.text
	.align	2
	.global	main
	.type	 main,function
main:
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 1, current_function_anonymous_args = 0
	mov	ip, sp
	stmfd	sp!, {r4, r5, r6, fp, ip, lr, pc}
	sub	fp, ip, #4
	mov	r5, #-2147483648
	mov	r4, #0
	ldr	r6, .L27
.L23:
	mov	r3, r5, asl #1
	orr	r5, r3, r5, lsr #31
	mov	r0, r6
	mov	r1, r4
	mov	r2, r5
	bl	printf
	add	r4, r4, #1
	cmp	r4, #63
	ble	.L23
	ldmea	fp, {r4, r5, r6, fp, sp, pc}
.L28:
	.align	2
.L27:
	.word	.LC0
.Lfe1:
	.size	 main,.Lfe1-main
	.ident	"GCC: (GNU) 2.95.3 20010315 (release)"
