# Default values for hello.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: hello-docker
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

nameOverride: ""
fullnameOverride: ""

service:
  type: NodePort
  port: 80
  nodePort: 30080
