# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='service.proto',
  package='pb',
  syntax='proto3',
  serialized_options=b'ZFgithub.com/egustafson/sandbox/_hybrid/grpc-error-handling/server-go/pb',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rservice.proto\x12\x02pb\"\x1e\n\nSvcRequest\x12\x10\n\x08req_text\x18\x01 \x01(\t\" \n\x0bSvcResponse\x12\x11\n\tresp_text\x18\x01 \x01(\t25\n\x03Svc\x12.\n\tDoService\x12\x0e.pb.SvcRequest\x1a\x0f.pb.SvcResponse\"\x00\x42HZFgithub.com/egustafson/sandbox/_hybrid/grpc-error-handling/server-go/pbb\x06proto3'
)




_SVCREQUEST = _descriptor.Descriptor(
  name='SvcRequest',
  full_name='pb.SvcRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='req_text', full_name='pb.SvcRequest.req_text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=51,
)


_SVCRESPONSE = _descriptor.Descriptor(
  name='SvcResponse',
  full_name='pb.SvcResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='resp_text', full_name='pb.SvcResponse.resp_text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=85,
)

DESCRIPTOR.message_types_by_name['SvcRequest'] = _SVCREQUEST
DESCRIPTOR.message_types_by_name['SvcResponse'] = _SVCRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SvcRequest = _reflection.GeneratedProtocolMessageType('SvcRequest', (_message.Message,), {
  'DESCRIPTOR' : _SVCREQUEST,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:pb.SvcRequest)
  })
_sym_db.RegisterMessage(SvcRequest)

SvcResponse = _reflection.GeneratedProtocolMessageType('SvcResponse', (_message.Message,), {
  'DESCRIPTOR' : _SVCRESPONSE,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:pb.SvcResponse)
  })
_sym_db.RegisterMessage(SvcResponse)


DESCRIPTOR._options = None

_SVC = _descriptor.ServiceDescriptor(
  name='Svc',
  full_name='pb.Svc',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=87,
  serialized_end=140,
  methods=[
  _descriptor.MethodDescriptor(
    name='DoService',
    full_name='pb.Svc.DoService',
    index=0,
    containing_service=None,
    input_type=_SVCREQUEST,
    output_type=_SVCRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SVC)

DESCRIPTOR.services_by_name['Svc'] = _SVC

# @@protoc_insertion_point(module_scope)
