# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\x02pb\"\x1e\n\nSvcRequest\x12\x10\n\x08req_text\x18\x01 \x01(\t\" \n\x0bSvcResponse\x12\x11\n\tresp_text\x18\x01 \x01(\t25\n\x03Svc\x12.\n\tDoService\x12\x0e.pb.SvcRequest\x1a\x0f.pb.SvcResponse\"\x00\x42HZFgithub.com/egustafson/sandbox/_hybrid/grpc-error-handling/server-go/pbb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'ZFgithub.com/egustafson/sandbox/_hybrid/grpc-error-handling/server-go/pb'
  _SVCREQUEST._serialized_start=21
  _SVCREQUEST._serialized_end=51
  _SVCRESPONSE._serialized_start=53
  _SVCRESPONSE._serialized_end=85
  _SVC._serialized_start=87
  _SVC._serialized_end=140
# @@protoc_insertion_point(module_scope)
