#!/usr/local/bin/perl

$0 = "foobar";

$sum = 0;

for ( $ii = 0; $ii < 65552; $ii++ ) {
    for ( $jj = 0; $jj < 65552; $jj++ ) {
        for ( $kk = 0; $kk < 65552; $kk++ ) {

            $sum = (($ii - $jj) * $kk) % 21;
        }
    }
}



exit;
