---
version: '3.3'

services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    user: "1000:1000"         # <- CHANGE
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./config:/mosquitto/config
      - ./data:/mosquitto/data
      - ./log:/mosquitto/log
...
