apiVersion: v1
kind: Service
metadata:
  name: {{ include "hello.fullname" . }}
  labels:
    {{- include "hello.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http-service-port
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: hello-port
      nodePort: {{ .Values.service.nodePort }}
  selector:
    {{- include "hello.selectorLabels" . | nindent 4 }}
