# This example demonstrates that a comment can 
# be embedded in the commands for a build target.
#

all: default
default:
	echo "There are 3 echo's following this"
	echo "1"
	# A comment in a sequence of commands
	echo "2"
# A comment not tabbed
	echo "3"

