module org { 
    module elfwerks {
        module sandbox {
            module servant { 
                interface PingService {
                    void ping();
                };
            };
        };
    };
};